name: Docker Image CI

on:
  push:
    branches: [ "Dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build opt/status-page/. --file Dockerfile --tag itayshlanger/status-page:latest
    - name: run the Docker Container
      run: docker run itayshlanger/status-page:latest
