name: Trigger Jenkins on PR to Dev

on:
  pull_request:
    branches:
      - Dev  # This will trigger the action when a PR targets the Dev branch

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins build
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
